// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

import Menu from "./menu/menu"
import styles from './styles.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <main className={styles.main}>
                    <Menu />
                    {children}
                </main>
            </body>
        </html>
    )
}
